// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

"use client";

import AnimatedSparkleIcon from "@/components/animated-sparkle";
import { Button } from "@/components/base/button";
import { useSession } from "@/hooks/session";
import { type ImageGalleryItem } from "@/lib/types";
import { capitalizeFirstLetter } from "@/lib/utils";
import { EllipsisVerticalIcon } from "@heroicons/react/20/solid";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getImagesByUserId } from "./actions";
import ImageOptions from "./image-options";

export default function MyImagesView() {
  const router = useRouter();
  const { user } = useSession();
  const [isLoading, setIsLoading] = useState(false);
  const [images, setImages] = useState<ImageGalleryItem[]>([]);
  const [imageToEdit, setImageToEdit] = useState<ImageGalleryItem | null>(null);
  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    if (user && user.uid) {
      setIsLoading(true);
      getImagesByUserId(user.uid)
        .then((data) => setImages(data as ImageGalleryItem[]))
        .catch((error) => {
          toast.error("Failed to fetch images");
          console.error(error);
        })
        .finally(() => setIsLoading(false));
    } else {
      setImages([]);
      setIsLoading(false);
    }
  }, [user]);

  return (
    <div className="py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2 className="text-slate text-4xl font-semibold tracking-tight text-pretty sm:text-5xl">
            Images Gallery
          </h2>
          <p className="text-black-300 mt-6 text-lg/8">
            {user && user.uid
              ? isLoading
                ? "Loading images..."
                : images.length > 0
                  ? "Here are the images generated by you over the time, so you can reference them quickly! View your creations and prompts at ease."
                  : "You do not have any images generated right now."
              : "Please sign in to view your images"}
          </p>

          {!isLoading && (
            <Button
              className="mt-5 ml-auto text-sm"
              onClick={() => router.push("/pixels")}
            >
              <AnimatedSparkleIcon className="h-3 w-3 fill-purple-400" />
              Generate more images!
            </Button>
          )}
        </div>

        <ul
          role="list"
          className="mx-auto mt-8 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-14 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3 xl:grid-cols-4"
        >
          {images.map((image, i) => (
            <li key={`image-${i}`}>
              <Link
                href={image.image_url}
                className="cursor-pointer"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src={image.image_url}
                  width={280}
                  height={260}
                  alt={image.prompt || ""}
                  className="aspect-14/13 w-full rounded-2xl border object-cover hover:opacity-80"
                />
              </Link>
              <h3 className="text-slate mt-6 line-clamp-1 text-xl/8 font-semibold tracking-tight sm:text-lg/8">
                {image.model_url ? (
                  <Link
                    href={image.model_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="cursor-pointer hover:text-blue-600 hover:underline"
                  >
                    {image.model.split(":")[0] ||
                      capitalizeFirstLetter(image.provider)}
                  </Link>
                ) : (
                  <span>
                    {image.model.split(":")[0] ||
                      capitalizeFirstLetter(image.provider)}
                  </span>
                )}
                <button
                  onClick={() => {
                    setImageToEdit(image);
                    setIsEditing(!isEditing);
                  }}
                  className="items-center"
                >
                  <EllipsisVerticalIcon className="mx-2 my-auto inline h-4 w-4 cursor-pointer text-slate-600" />
                </button>
              </h3>
              {image.prompt && (
                <p className="text-black-500 prose text-md/6 line-clamp-4 text-pretty sm:text-sm/6">
                  {image.prompt}
                </p>
              )}
            </li>
          ))}
        </ul>

        {imageToEdit && (
          <ImageOptions
            image={imageToEdit}
            isOpen={isEditing}
            setIsOpen={setIsEditing}
          />
        )}
      </div>
    </div>
  );
}
