// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

"use client";

import AnimatedSparkleIcon from "@/components/animated-sparkle";
import { Button } from "@/components/base/button";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";

interface MyImagesViewProps {
  images: {
    imageUrl: string;
    alt?: string;
  }[];
}

export default function MyImagesView({ images }: MyImagesViewProps) {
  const router = useRouter();
  if (!images.length) {
    return (
      <div className="py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl lg:mx-0">
            <h2 className="text-slate text-4xl font-semibold tracking-tight text-pretty sm:text-5xl">
              Images Gallery
            </h2>
            <p className="text-black-300 mt-6 text-lg/8">
              You do not have any images generated right now.
            </p>
          </div>
          <Button
            className="my-1 mt-12 ml-auto max-h-10 text-sm"
            onClick={() => router.push("/pixels")}
          >
            <AnimatedSparkleIcon className="h-3 w-3 fill-purple-400" />
            Go Generate!
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2 className="text-slate text-4xl font-semibold tracking-tight text-pretty sm:text-5xl">
            Images Gallery
          </h2>
          <p className="text-black-300 mt-6 text-lg/8">
            Here are the images generated by you over the time, so you can
            reference them quickly! View your creations and prompts at ease.
          </p>
        </div>
        <ul
          role="list"
          className="mx-auto mt-20 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-14 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3 xl:grid-cols-4"
        >
          {images.map((image, i) => (
            <li key={`image-${i}`}>
              <Link
                href={image.imageUrl}
                className="cursor-pointer"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src={image.imageUrl}
                  width={280}
                  height={260}
                  alt={image.alt || ""}
                  className="aspect-14/13 w-full rounded-2xl border object-cover"
                />
                {/* {image.title && (
                  <h3 className="text-slate mt-6 text-lg/8 font-semibold tracking-tight">
                    {image.title}
                  </h3>
                )}
                {image.subtitle && (
                  <p className="text-black-300 text-base/7">{image.subtitle}</p>
                )}
                {image.footer && (
                  <p className="text-black-500 text-sm/6">{image.footer}</p>
                )} */}
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
