// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { getLanguageModel } from '@/lib/models';
import { checkRateLimit } from '@/lib/redis';
import { claimsSchema } from '@/lib/schema';
import { LanguageModel, streamObject } from 'ai';
import { NextResponse } from 'next/server';

// Allow streaming responses up to 30 seconds
export const maxDuration = 30;

const systemPrompt = `
WW91IGFyZSBhbiBleHBlcnQgZmFjdC1jaGVja2VyIGF0IGEgbmV3c3BhcGVyLiBZb3VyIGpvYiBpcyB0byBpZGVudGlmeSBlYWNoIGZhY3RvaWQgaW4gdGhlIFNlbnRlbmNlLiBUaGVuIGRlY29udGV4dHVhbGl6ZSBlYWNoIGZhY3RvaWQgYW5kIHdyaXRlIHRoZSBmYWN0b2lkIGFzIGEgc3RhbmRhbG9uZSBzZW50ZW5jZSB0aGF0IGNvbnRhaW5zIG9ubHkgdGhhdCBmYWN0b2lkLiAKCioqTWFuZGF0b3J5KioKCiogT25seSBnZW5lcmF0ZSBmYWN0b2lkIGV4cGxpY2l0bHkgb3IgaW1wbGljaXRseSBpbXBsaWVkIGluIHRoZSBvcmlnaW5hbCBzZW50ZW5jZS4KKiBJZiBhbiBlbnRpdHkgaXMgbWVudGlvbmVkLiBhYnNvbHV0ZWx5IGRvIE5PVCBkcmF3IG91dHNpZGUga25vd2xlZGdlIHRvIGV4cGxhaW4gY29uY2VwdHMsIHVubGVzcyBpdCdzIGV4cGxhaW5lZCBkaXJlY3RseSBpbiB0aGUgb3JpZ2luYWwgc2VudGVuY2UuCiogRG8gbm90IGdlbmVyYXRlIGdlbmVyaWMgY2xhaW1zIHN1Y2ggYXMgInh4eCBpcyBtZW50aW9uZWQiCiogSWYgaW5wdXQgbWFkZSBubyBjbGFpbXMsIGRvIG5vdCBnZW5lcmF0ZSBjbGFpbXMuCgo9PT0gRXhhbXBsZSAxID09PQoKVXNlcjogY2FuIHlvdSBnaXZlIG1lIHNvbWUgZXhhbXBsZXMgb2Ygc2NpZW5jZSBmaWN0aW9uIG1vdmllcz8KUHJlZml4OiBTdXJlISBIZXJlIGFyZSBzb21lIGV4YW1wbGVzOgoKKiBCYWNrIHRvIHRoZSBGdXR1cmUgKDE5ODUpIGRpcmVjdGVkIGJ5IFJvYmVydCBaZW1lY2tpcy4KKiBUaGUgRmx5ICgxOTg4KSBkaXJlY3RlZCBieSBEYXZpZCBDcm9uZW5iZXJnLgoKU2VudGVuY2U6ICogSW50ZXJzdGVsbGFyICgyMDE0KSBkaXJlY3RlZCBieSBDaHJpc3RvcGhlciBOb2xhbi4KClJld3JpdHRlbiBmYWN0cyBmcm9tIFNlbnRlbmNlOgpGYWN0OiBJbnRlcnN0ZWxsYXIgaXMgYSBzY2llbmNlIGZpY3Rpb24gbW92aWUuCkZhY3Q6IEludGVyc3RlbGxhciB3YXMgcmVsZWFzZWQgaW4gMjAxNC4KRmFjdDogQ2hyaXN0b3BoZXIgTm9sYW4gZGlyZWN0ZWQgSW50ZXJzdGVsbGFyLgoKPT09IEV4YW1wbGUgMiA9PT0KClVzZXI6IFdoYXQgc2hvd3MgaGFzIENvdXJ0bmV5IENveCBhY3RlZCBvbj8KUHJlZml4OiBDb3VydGVuZXkgQ294IGhhcyBhY3RlZCBvbiBhIHZhcmlldHkgb2Ygc2hvd3Mgb3ZlciB0aGUgeWVhcnMsIGluY2x1ZGluZzoKCiogTWlzZml0cyBvZiBTY2llbmNlICgxOTg1KTogQ294IHN0YXJyZWQgYXMgR2xvcmlhIERpbmFsbG8gaW4gdGhpcyBzaG9ydC1saXZlZCBOQkMgc2NpZW5jZSBmaWN0aW9uIGZhbnRhc3kgc2VyaWVzLgoqIEZhbWlseSBUaWVzICgxOTg34oCTMTk4OSk6IENveCBoYWQgYSByZWN1cnJpbmcgcm9sZSBhcyBMYXVyZW4gTWlsbGVyLgoKU2VudGVuY2U6ICogRnJpZW5kcyAoMTk5NOKAkzIwMDQpOiBDb3ggaXMgYmVzdCBrbm93biBmb3IgaGVyIHJvbGUgYXMgTW9uaWNhIEdlbGxlciBpbiB0aGlzIE5CQyBzaXRjb20uCgpSZXdyaXR0ZW4gZmFjdHMgZnJvbSBTZW50ZW5jZToKRmFjdDogQ291cnRuZXkgQ294IGFjdGVkIG9uIHRoZSBUViBzaG93IEZyaWVuZHMuCkZhY3Q6IENvdXJ0bmV5IENveCBwbGF5ZWQgdGhlIHJvbGUgb2YgTW9uaWNhIEdlbGxlciBvbiBGcmllbmRzLgpGYWN0OiBGcmllbmRzIGFpcmVkIGZyb20gMTk5NCB0byAyMDA0LgpGYWN0OiBGcmllbmRzIGlzIGEgc2l0Y29tLgpGYWN0OiBGcmllbmRzIHdhcyBwcm9kdWNlZCBieSBOQkMuCgo9PT0gRXhhbXBsZSAzID09PQoKVXNlcjogVGVsbCBtZSBhYm91dCBDaGFybGVzIExlY2xlcmMuClByZWZpeDogQ2hhcmxlcyBMZWNsZXJjIGlzIGEgTW9uw6lnYXNxdWUgcmFjaW5nIGRyaXZlciB3aG8gY3VycmVudGx5IHJhY2VzIGluIEZvcm11bGEgT25lIGZvciBTY3VkZXJpYSBGZXJyYXJpLiBIZSB3b24gdGhlIEdQMyBTZXJpZXMgY2hhbXBpb25zaGlwIGluIDIwMTYgYW5kIHRoZSBGSUEgRm9ybXVsYSAyIENoYW1waW9uc2hpcCBpbiAyMDE3LiBIZSBtYWRlIGhpcyBGb3JtdWxhIE9uZSBkZWJ1dCBpbiAyMDE4IGZvciBTYXViZXIsIGEgdGVhbSBhZmZpbGlhdGVkIHdpdGggRmVycmFyaSwgZm9yIHdoaWNoIGhlIHdhcyBwYXJ0IG9mIHRoZSBGZXJyYXJpIERyaXZlciBBY2FkZW15LgoKU2VudGVuY2U6IFdpdGggU2F1YmVyIGhhdmluZyBmaW5pc2hlZCBsYXN0IHRoZSB5ZWFyIGJlZm9yZSwgTGVjbGVyYyBsZWQgdGhlIGNoYXJnZSB0byBpbXByb3ZlIGl0cyBmaW5pc2hpbmcgcG9zaXRpb24gaW4gdGhlIENvbnN0cnVjdG9ycycgQ2hhbXBpb25zaGlwIHRvIGVpZ2h0aCwgYW5kIHdhcyB0aGUgaGlnaGVyIHJhbmtlZCBvZiB0aGUgdHdvIFNhdWJlciBkcml2ZXJzLgoKUmV3cml0dGVuIGZhY3RzIGZyb20gU2VudGVuY2U6CkZhY3Q6IFNhdWJlciBmaW5pc2hlZCBsYXN0IGluIHRoZSAyMDE3IEZvcm11bGEgT25lIENvbnN0cnVjdG9yc+KAmSBDaGFtcGlvbnNoaXAuCkZhY3Q6IEluIDIwMTgsIENoYXJsZXMgTGVjbGVyYyBsZWQgdGhlIGNoYXJnZSB0byBpbXByb3ZlIFNhdWJlcidzIGZpbmlzaGluZyBwb3NpdGlvbiBpbiB0aGUgQ29uc3RydWN0b3JzJyBDaGFtcGlvbnNoaXAuCkZhY3Q6IFNhdWJlciBmaW5pc2hlZCBlaWdodGggaW4gdGhlIDIwMTggRm9ybXVsYSBPbmUgQ29uc3RydWN0b3Jz4oCZIENoYW1waW9uc2hpcC4KRmFjdDogSW4gMjAxOCwgU2F1YmVyIGhhZCB0d28gZHJpdmVycy4KRmFjdDogSW4gMjAxOCwgQ2hhcmxlcyBMZWNsZXJjIHdhcyB0aGUgaGlnaGVyIHJhbmtlZCBvZiB0d28gU2F1YmVyIGRyaXZlcnMuCgo9PT0gRXhhbXBsZSA0ID09PQoKVXNlcjogR2l2ZSBtZSB0aGUgc3RlcHMgdG8gYWN0aXZhdGUgbG9jYXRpb24gcHJlZmVyZW5jZXMgb24gdGhlIGlwaG9uZS4KUHJlZml4OiBTdXJlLCBoZXJlIGFyZSB0aGUgc3RlcHMgb24gaG93IHRvIGFjdGl2YXRlIGxvY2F0aW9uIHByZWZlcmVuY2VzIG9uIHlvdXIgaVBob25lOgoKMS4gT3BlbiB0aGUgU2V0dGluZ3MgYXBwLgoyLiBUYXAgb24gUHJpdmFjeS4KClNlbnRlbmNlOiAzLiBUYXAgb24gTG9jYXRpb24gU2VydmljZXMuCgpSZXdyaXR0ZW4gZmFjdHMgZnJvbSBTZW50ZW5jZToKRmFjdDogVGhlIHRoaXJkIHN0ZXAgdG8gYWN0aXZhdGUgbG9jYXRpb24gcHJlZmVyZW5jZXMgb24gdGhlIGlwaG9uZSBpcyB0byB0YXAgb24gTG9jYXRpb24gU2VydmljZXMuCkZhY3Q6IExvY2F0aW9uIFNlcnZpY2VzIGlzIGxvY2F0ZWQgaW4gUHJpdmFjeSBpbiB0aGUgU2V0dGluZ3MgYXBwIG9uIHRoZSBpcGhvbmUuCgo9PT0gRXhhbXBsZSA1ID09PQoKVXNlcjogV2hhdCBhcmUgZ29vZCBkaWV0YXJ5IHNvdXJjZXMgb2YgemluYz8KUHJlZml4OiBaaW5jIGlzIGFuIGVzc2VudGlhbCBtaW5lcmFsIHRoYXQgeW91ciBib2R5IG5lZWRzIGZvciBtYW55IGltcG9ydGFudCBmdW5jdGlvbnMsIGluY2x1ZGluZzoKCiogSW1tdW5lIHN5c3RlbSBmdW5jdGlvbgoqIENlbGwgZ3Jvd3RoIGFuZCBkaXZpc2lvbgoqIFdvdW5kIGhlYWxpbmcgKiBNZXRhYm9saXNtCiogRmVydGlsaXR5CiogU21lbGwgYW5kIHRhc3RlCgpaaW5jIGlzIG5vdCBzdG9yZWQgaW4gdGhlIGJvZHksIHNvIGl0IGlzIGltcG9ydGFudCB0byBnZXQgaXQgZnJvbSB5b3VyIGRpZXQgb24gYSByZWd1bGFyIGJhc2lzLiBHb29kIGRpZXRhcnkgc291cmNlcyBvZiB6aW5jIGluY2x1ZGU6CgoqICoqTWVhdDoqKiBCZWVmLCBsYW1iLCBwb3JrLCBjaGlja2VuLCBhbmQgdHVya2V5LgoqICoqU2VhZm9vZDoqKiBPeXN0ZXJzLCBjcmFiLCBsb2JzdGVyLCBhbmQgc2hyaW1wLgoKU2VudGVuY2U6ICogKipMZWd1bWVzOioqIEJlYW5zLCBsZW50aWxzLCBhbmQgcGVhcy4KClJld3JpdHRlbiBmYWN0cyBmcm9tIFNlbnRlbmNlOgpGYWN0OiBMZWd1bWVzIGFyZSBhIGdvb2QgZGlldGFyeSBzb3VyY2Ugb2YgemluYy4KRmFjdDogQmVhbnMgYXJlIGEgZ29vZCBkaWV0YXJ5IHNvdXJjZSBvZiB6aW5jLgpGYWN0OiBMZW50aWxzIGFyZSBhIGdvb2QgZGlldGFyeSBzb3VyY2Ugb2YgemluYy4KRmFjdDogUGVhcyBhcmUgYSBnb29kIGRpZXRhcnkgc291cmNlIG9mIHppbmMuCkZhY3Q6IEJlYW5zIGFyZSBsZWd1bWVzLgpGYWN0OiBMZW50aWxzIGFyZSBsZWd1bWVzLgpGYWN0OiBQZWFzIGFyZSBsZWd1bWVzLgoKPT09IEV4YW1wbGUgNiA9PT0KClVzZXI6IHdobyBpcyBuZWhydT8KUHJlZml4OiBKYXdhaGFybGFsIE5laHJ1IC0gSW5kaWFuIHN0YXRlc21hbiBhbmQgcG9saXRpY2FsIGxlYWRlci4gT25lIG9mIHRoZSBtb3N0IHByb21pbmVudCBwb2xpdGljYWwgZmlndXJlcyBpbiB0aGUgd29ybGQsIGhlIHdhcyB0aGUgbGVhZGVyIG9mIHRoZSBsZWZ0IHdpbmcgb2YgdGhlIEluZGlhbiBuYXRpb25hbCBsaWJlcmF0aW9uIG1vdmVtZW50LiBVbmRlciB0aGUgbWVudG9yc2hpcCBvZiBNYWhhdG1hIEdhbmRoaSwgTmVocnUgYmVjYW1lIGNoYWlybWFuIG9mIHRoZSBJbmRpYW4gTmF0aW9uYWwgQ29uZ3Jlc3MsIGFuZCBsYXRlciwgYWZ0ZXIgdGhlIGNvdW50cnkgZ2FpbmVkIGluZGVwZW5kZW5jZSBvbiBBdWd1c3QgMTUsIDE5NDcsIHRoZSBmaXJzdCBwcmltZSBtaW5pc3RlciBvZiBJbmRpYS4KClNlbnRlbmNlOiBIZSByZW1haW5lZCBpbiB0aGlzIHBvc3QgdW50aWwgTWF5IDI3LCAxOTY0LCB3aGVuIGhlIGRpZWQgb2YgYSBoZWFydCBhdHRhY2suCgpSZXdyaXR0ZW4gZmFjdHMgZnJvbSBTZW50ZW5jZToKRmFjdDogSmF3YWhhcmxhbCBOZWhydSByZW1haW5lZCB0aGUgcHJpbWUgbWluaXN0ZXIgb2YgSW5kaWEgdW50aWwgTWF5IDI3LCAxOTY0LgpGYWN0OiBKYXdhaGFybGFsIE5laHJ1IGRpZWQgb2YgYSBoZWFydCBhdHRhY2suCkZhY3Q6IEphd2FoYXJsYWwgTmVocnUgZGllZCBvbiBNYXkgMjcsIDE5NjQuCgo9PT0gRXhhbXBsZSA3ID09PQoKVXNlcjogdGVsbCBtZSBhYm91dCBzZWFycwpQcmVmaXg6IFNlYXJzIEhvbGRpbmdzLCBiYXNlZCBpbiBIb2ZmbWFuIEVzdGF0ZXMsIElsbGlub2lzLCBsb3N0ICQ0MjQgbWlsbGlvbiwgb3IgJDMuOTMgcGVyIHNoYXJlLCBpbiBpdHMgZmlyc3QgcXVhcnRlci4gVGhlIFdlc3QgRHVsdXRoIEttYXJ0IGlzIHRoZSBjaGFpbidzIGxhc3QgbG9jYXRpb24gaW4gdGhlIFR3aW4gUG9ydHMgYXJlYSBhZnRlciB0aGUgY2xvc3VyZSBvZiBzdG9yZXMgaW4gRHVsdXRoIEhlaWdodHMgYW5kIFN1cGVyaW9yLiAiSXQgaXMgZ29pbmcgdG8gYmUgYSBiaWcgbG9zcywiIHNhaWQgTG9yZXR0YSBPbHNlbiwgd2hvIHNob3BzIGF0IGJvdGggc3RvcmVzLiAiVGhlIHN0b3JlcyBhcmUgc2xvd2x5IGNsb3NpbmcgYW5kIHdoZXJlIGFtIEkgZ29pbmcgdG8gZ28gc2hvcHBpbmcuIEkgZG9uJ3Qgd2FudCB0byBzaG9wIG9ubGluZS4iCgpTZW50ZW5jZTogU3VzYW4gQ29lbiwgUHJlc2lkZW50IG9mIHRoZSBXZXN0IER1bHV0aCBCdXNpbmVzcyBDbHViIHNheXMgaXQncyBnb2luZyB0byBpbXBhY3QgdGhlIGdyb3d0aCBvZiB0aGUgYXJlYSBhcyB3ZWxsLgoKUmV3cml0dGVuIGZhY3RzIGZyb20gU2VudGVuY2U6CkZhY3Q6IFN1c2FuIENvZW4gaXMgdGhlIFByZXNpZGVudCBvZiB0aGUgV2VzdCBEdWx1dGggQnVzaW5lc3MgQ2x1Yi4KRmFjdDogQWNjb3JkaW5nIHRvIFN1c2FuIENvZW4sIHRoZSBjbG9zdXJlIG9mIEttYXJ0IHN0b3JlcyBpbiBEdWx1dGggSGVpZ2h0cyBhbmQgU3VwZXJpb3IgaXMgZ29pbmcgdG8gaW1wYWN0IHRoZSBncm93dGggb2YgdGhlIER1bHV0aCBhcmVhLgoKPT0gRXhhbXBsZSA4ID09ClVzZXI6IHdobyBpcyBwcmVzaWRlbnQgb2JhbWEncyBhZ2UKUHJlZml4OgoKU2VudGVuY2U6IFByZXNpZGVudCBvYmFtYSBpcyA2MyB5ZWFycyBvbGQuIEhlIGlzIHRoZSA0NHRoIFUuUyBwcmVzaWRlbnQuCgpSZXdyaXR0ZW4gZmFjdHMgZnJvbSBTZW50ZW5jZToKRmFjdDogUHJlc2lkZW50IG9iYW1hIGlzIHRoZSA0NHRoIFUuUyBwcmVzaWRlbnQuCkZhY3Q6IFByZXNpZGVudCBvYmFtYSBpcyBtYWxlLgpGYWN0OiBQcmVzaWRlbnQgb2JhbWEgaXMgNjMgeWVhcnMgb2xkLgoKPT0gRXhhbXBsZSA5ID09ClVzZXI6ClByZWZpeDoKClNlbnRlbmNlOiBmb28sIGJhciwgYW5kIGJhegoKUmV3cml0dGVuIGZhY3RzIGZyb20gU2VudGVuY2U6Ck5vIGZhY3RzIGNsYWltZWQu
`

export async function POST(req: Request) {
  const context = await req.json();
  const headers = req.headers;
  const modelChoice = headers.get('X-AI-Model') || 'gpt-4o-mini'

  let { passed, secondsLeft } = await checkRateLimit("/api/ai-claims")
  if (!passed) {
    return NextResponse.json({
      error: `Rate Limited. ${secondsLeft && `${secondsLeft}s left`}.`
    }, { status: 429 })
  }

  let model: LanguageModel | null = null;
  try {
    model = getLanguageModel(modelChoice)
  } catch (error) {
    console.error(error)
    return NextResponse.json({ error: (error as Error).message }, { status: 400 })
  }

  const result = await streamObject({
    model: model,
    schema: claimsSchema,
    system: Buffer.from(systemPrompt.trim(), 'base64').toString('utf-8'),
    prompt: context.trim(),
  })
  return result.toTextStreamResponse();
}